#!/bin/bash
if [ $# -ne 1 ] && [ $# -ne 2 ]
then
    echo "Usage : $0 <youtube_file_link>"
    echo "e.g : $0 http://www.youtube.com/watch?v=D1R-jKKp3NA"
else
    #Some safety so we don't run this a bajillion times
    omx=`pgrep omxplayer | wc -l`
    yt=`pgrep youtube | wc -l`
    ytsearch=`pgrep youtube-search | wc -l`
    yt=$((yt - ytsearch))
    if [[ "$omx" -gt 0 ]] || [[ $yt -gt 2 ]] ; then
        exit 0
    fi
    if [ -z $DISPLAY ] ; then
        run_command="omxplayer -r -o hdmi"
    else
        run_command="xterm -fullscreen -bg black -fg black -e omxplayer -r -o hdmi"
    fi

    #check to see if fifo exists (if this is really big, I'll have to move it out of /dev/shm.
    BUFFER_TIME=5
    STREAM_FIFO="/dev/shm/temp.stream"
    if [ ! -e $STREAM_FIFO ]; then
        mkfifo $STREAM_FIFO
    fi

    var=$1

    #check to see if we should use get_flash_videos instead
    other=`echo "$var" | grep "hulu\|vimeo" | wc -l`
    if [[ "$other" -eq 0 ]] ; then
        http=`echo "$var" | grep "http\|ytb" | wc -l`
        if [[ "$http" -eq 0 ]] ; then
            count=`echo "$var" | wc -l`
            num=1
            while [ $num -le $count ] ;
            do
                video=`echo "$var" | head -n $num | tail -n 1`
                if [[ "$video" == yt* ]] ; then
                    video="${video/yt/http}"
                fi
                todnload=`youtube-dl -i -g --cookies /dev/shm/youtube_cookie.txt "$video"`
                wget -O "$STREAM_FIFO" "$todnload" & 1>/dev/null 2>/dev/null
                sleep $BUFFER_TIME
                $run_command "$STREAM_FIFO"
                num=`expr $num + 1`
            done
        else
            list=`echo "$var" | grep list | wc -l`
            if [[ list -eq 0 ]] ; then
                if [[ "$var" == yt* ]] ; then
                    var="${var/yt/http}"
                fi
                todnload=`youtube-dl -i -g --cookies /dev/shm/youtube_cookie.txt "$var"`
                tot=`echo "$todnload" | wc -l`
                num=1
                while [ $num -le $tot ] ; 
                do
                    echo "$num out of $tot"
                    link=`echo "$todnload" | head -n $num | tail -n 1`
                    wget -O "$STREAM_FIFO" "$link" & 1>/dev/null 2>/dev/null
                    sleep $BUFFER_TIME
                    $run_command "$STREAM_FIFO"
                    num=`expr $num + 1`
                done
            else
                echo "Youtube playlist ..."
                num=1
                if [[ "$var" == yt* ]] ; then
                    var="${var/yt/http}"
                fi
                todnload=`youtube-dl -g --cookies /dev/shm/youtube_cookie.txt --playlist-start $num --playlist-end $num "$var"`
                while [ "$todnload" != "" ] ; 
                do
                    wget -O "$STREAM_FIFO" "$todnload" & 1>/dev/null 2>/dev/null
                    sleep $BUFFER_TIME
                    $run_command "$STREAM_FIFO"
                    num=`expr $num + 1`
                    if [[ "$var" == yt* ]] ; then
                        var="${var/yt/http}"
                    fi
                    todnload=`youtube-dl -g --cookies /dev/shm/youtube_cookie.txt --playlist-start $num --playlist-end $num "$var"`
                done
            fi
        fi
    else
        echo "Using get_flash_videos"
        get_flash_videos -f "$STREAM_FIFO" -q -y "$var" & 1>/dev/null 2>/dev/null
        sleep 1
        $run_command "$STREAM_FIFO"
    fi
    rm $STREAM_FIFO
fi
