#!/bin/bash
if [ $# -ne 1 ] && [ $# -ne 2 ]
then
    echo "Usage : $0 <youtube_file_link>"
    echo "e.g : $0 http://www.youtube.com/watch?v=D1R-jKKp3NA"
else
    if [ -z $DISPLAY ] ; then
        run_command="omxplayer -r -o hdmi"
    else
        run_command="xterm -fullscreen -bg black -fg black -e omxplayer -r -o hdmi"
    fi
    var=$1
    http=`echo "$var" | grep http | wc -l`
    if [[ http -eq 0 ]] ; then
        count=`cat "$var" | wc -l`
        num=1
        while [ $num -le $count ] ;
        do
            video=`cat "$var" | head -n $num | tail -n 1`
            $run_command "$video"
            num=`expr $num + 1`
        done
    else
    list=`echo "$var" | grep list | wc -l`
    if [[ list -eq 0 ]] ; then
        todnload=`youtube-dl -i -g --cookies /dev/shm/youtube_cookie.txt "$var"`
        tot=`echo "$todnload" | wc -l`
        num=1
        while [ $num -le $tot ] ; 
        do
            echo "$num out of $tot"
            link=`echo "$todnload" | head -n $num | tail -n 1`
            $run_command "$link"
            num=`expr $num + 1`
        done
    else
        echo "Youtube playlist ..."
        num=1
        todnload=`youtube-dl -g --cookies /dev/shm/youtube_cookie.txt --playlist-start $num --playlist-end $num "$var"`
        while [ "$todnload" != "" ] ; 
        do
            $run_command "$todnload"
            num=`expr $num + 1`
            todnload=`youtube-dl -g --cookies /dev/shm/youtube_cookie.txt --playlist-start $num --playlist-end $num "$var"`
        done
    fi
    fi
fi
